### PR TITLE
fixes #317

### LINKED ISSUE #317: additional_userdata script needs '#!/bin/sh at top to work with AL2023 AMI
### Terraform Version Details

_No response_

### Terraform Variable File Details

_No response_

### Steps to Reproduce

update to an AMI using AL2023 for the compute node pool

include "custom_data" = "files/custom-data/additional_userdata.sh" in compute node pool definition within terraform.tfvars

### Expected Behavior

NVME drives should mount and be available at the /nvme/disk symlink.

### Actual Behavior

cloud-init won't run the scripts-user module during config, it fails with this error

Exec format error. Missing #! in script
 
Googling a bit I came across this [post](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Frepost.aws%2Fquestions%2FQUFWDJ6WFSSzarr2GeW0Td_w%2Fcloud-init-script-is-not-being-run-on-amazon-linux-2023&data=05%7C02%7CPhilip.Hopkins%40sas.com%7Ceaad66f23bab42b527dd08dd317e5db7%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C638721140983000519%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=tgXLcyGAwGYMYGepGIasBpNLRcj%2FYr9FIUAMqAxKTso%3D&reserved=0), 

which suggests we simply need to add #!/bin/sh to the top of our additional_userdata.sh script in order for cloud-init to execute it.  This wasn’t necessary on AL2 images, but apparently is needed for AL2023.

### Additional Context

_No response_

### References

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joshcoburn**
Fixes #317

Credit to @canpmh for the solution.

### CODE REVIEW

**Comment by saschjmil** [comment]
This looks good to me. Thanks for fixing it @joshcoburn! I'm going to update the target branch to staging. Before I approve it, could you do two things?
1. Could you update your branch so it isn't out of date with the base branch? There should be a button on this PR that does it for you.
2. Could you sign off on your commit so the DCO check passes? There is more info here: https://github.com/sassoftware/viya4-iac-aws/pull/320/checks?check_run_id=36481304976

File: files/custom-data/additional_userdata.sh [hunk 1]
```diff
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 # Copyright 2021-2023, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
```
Comment (saschjmil) [inline files/custom-data/additional_userdata.sh:3]: Also, could you update the copyright on this file?
```suggestion
# Copyright 2021-2025, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
```

**Review by saschjmil — APPROVED** [review]
I went ahead and committed the copyright fix and signed off on it. Looks good to me

File: files/custom-data/additional_userdata.sh [hunk 2]
```diff
@@ -1,4 +1,6 @@
-# Copyright 2021-2023, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
+#!/bin/bash
```
Comment (illianov) [inline files/custom-data/additional_userdata.sh:1]: do we want to standardize the shebang for bash for all bash scripts in the repo? Looks like the path varies in some of the other bash scripts.

**Review by dhoucgitter — APPROVED** [review]
looks good to me

File: files/custom-data/additional_userdata.sh (hunk 2 above)
Comment (dhoucgitter) [reply files/custom-data/additional_userdata.sh]: @saschjmil, I'm concerned that the bash path Phil provided is the right one to use for AL2023 since it sounds like he verified it. Maybe we should ask Phil before updating it to another value?

Comment (saschjmil) [reply files/custom-data/additional_userdata.sh]: @dhoucgitter, that works for me. I tested using both the shebangs and it seemed to be identical. But it wouldn't hurt to double check.

@canpmh, do you know if using `#!/usr/bin/env bash` over `#!/bin/bash` would cause any issues? Ideally I'd like to keep the shebangs the same across the project, but if it would cause issues, I'm happy to switch it back to `#!/bin/bash`

**Comment by canpmh** [comment]
Hey guys,

Standardizing across all of your scripts seems like a good idea.

As for this one, the OP where I found the solution online tested with /bin/bash.  In my current cluster on an AL2023 i4i.4xlarge instance, I’ve used /bin/sh and that also works.

If your standard is /usr/bin/bash, let me know, I could test that for you if you like.

Phil

Get Outlook for Mac <https://aka.ms/GetOutlookForMac>

**Comment by saschjmil** [comment]
Thanks for the insight @canpmh. The shebang we've used in our other bash scripts is `#!/usr/bin/env bash`. I updated this PR because it was originally using `#!/bin/bash`, but as David pointed out, that may have some unintended consequences. If you are willing to test out the new `#!/usr/bin/env bash` shebang, I would greatly appreciate it 😄

**Comment by canpmh** [comment]
It seems to have worked using #/usr/bin/env bash

Here is a look around the node:

***@***.*** disk]# nvme list

Node             SN                   Model                                    Namespace Usage                      Format           FW Rev

---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------

/dev/nvme0n1     vol0039b9f1f1d38e0cf Amazon Elastic Block Store               1         214.75  GB / 214.75  GB    512   B +  0 B   2.0

/dev/nvme1n1     AWS2402605ECBD365703 Amazon EC2 NVMe Instance Storage         1           1.88  TB /   1.88  TB    512   B +  0 B   0

***@***.*** disk]# df -h | grep nvme

/dev/nvme0n1p1    200G   44G  157G  22% /

/dev/nvme0n1p128   10M  1.3M  8.7M  13% /boot/efi

/dev/nvme1n1      1.7T   36K  1.7T   1% /pv-disks/b4f76f78-96bf-4d37-8850-5d5d33b6a3da

***@***.*** nvme]# cd /nvme

***@***.*** nvme]# ll

total 0

lrwxrwxrwx. 1 root root 46 Mar 27 16:45 disk -> /pv-disks/b4f76f78-96bf-4d37-8850-5d5d33b6a3da

***@***.*** nvme]#

***@***.*** nvme]# cd disk

***@***.*** disk]# ll

total 24

drwxrwxrwx. 2 nobody nobody  4096 Mar 27 16:45 cache

drwxrwxrwx. 2 nobody nobody 16384 Mar 27 16:45 lost+found

drwxrwxrwx. 2 nobody nobody  4096 Mar 27 16:45 saswork

**Comment by saschjmil** [comment]
Awesome, thanks so much for testing it. Since everything looks good, I'm good to merge this. @dhoucgitter, does that work for you?

**Comment by dhoucgitter** [comment]
> Awesome, thanks so much for testing it. Since everything looks good, I'm good to merge this. @dhoucgitter, does that work for you?

@saschjmil, I'm good with that Chris, thanks for checking the alternate value @canpmh!
